export const decors = [
  {
    id: 1,
    title: "Bohemian Wall Hanging Wood Shelf",
    url: 'https://angelicatrumbower.github.io/Knot-Home/Macrame/shelf.jpg',
    originalPrice: 49.95,
    salePrice: 18.95,
    rating: 4.5,
  },
  {
    id: 2,
    title: "Boho Tie-Dye Wall Decor",
    url: 'https://angelicatrumbower.github.io/Knot-Home/Macrame/large%20wall%20hanging.jpg',
    originalPrice: 39,
    salePrice: null,
    rating: 5,
  },
  {
    id: 3,
    title: "Bohemian Photo Display",
    url: 'https://angelicatrumbower.github.io/Knot-Home/Macrame/picture%20frame.jpg',
    originalPrice: 29,
    salePrice: 19.95,
    rating: 5,
  },
  {
    id: 4,
    title: "Tree of Life Wall Decor",
    url: 'https://angelicatrumbower.github.io/Knot-Home/Macrame/tree%20of%20life%20wall%20hang.jpg',
    originalPrice: 54,
    salePrice: 34.95,
    rating: 4.5,
  },
  {
    id: 5,
    title: "Rustic Chic Nature Leaves Display",
    url: 'https://angelicatrumbower.github.io/Knot-Home/Macrame/LEAVES.jpg',
    originalPrice: 40,
    salePrice: 19.95,
    rating: 5,
  },
  {
    id: 6,
    title: "Boho Chic Wooden Disc",
    url: 'https://angelicatrumbower.github.io/Knot-Home/Macrame/wood%20circles%20wall%20hang.jpg',
    originalPrice: 30,
    salePrice: 15.50,
    rating: 5,
  },
  {
    id: 7,
    title: "Macrame Keychain Wristlet",
    url: 'https://angelicatrumbower.github.io/Knot-Home/Macrame/wristlet.jpg',
    originalPrice: 11,
    salePrice: 10,
    rating: 4,
  },
  {
    id: 8,
    title: "Dream Catcher Moon Wall Decor",
    url: 'https://angelicatrumbower.github.io/Knot-Home/Macrame/dream%20catcher%20moon.jpg',
    originalPrice: 38,
    salePrice: 25.95,
    rating: 4.5,
  },
  {
    id: 9,
    title: "Bohemian Leaf Pattern Curtain",
    url: 'https://angelicatrumbower.github.io/Knot-Home/Macrame/curtains.jpg',
    originalPrice: 24.95,
    salePrice: null,
    rating: 5,
  },
  {
    id: 10,
    title: "Mountain Wall Hanging Taspestry",
    url: 'https://angelicatrumbower.github.io/Knot-Home/Macrame/mountain%20wall%20hanging.jpg',
    originalPrice: 40,
    salePrice: null,
    rating: 4,
  },
  {
    id: 11,
    title: "Bohemian Accent Leaf Wall Decor",
    url: 'https://angelicatrumbower.github.io/Knot-Home/Macrame/leaves%20with%20backdrop.jpg',
    originalPrice: 27.95,
    salePrice: null,
    rating: 4.5,
  },
  {
    id: 12,
    title: "Boho Chic Plant Holder Trio",
    url: 'https://angelicatrumbower.github.io/Knot-Home/Macrame/plant%20holders.jpg',
    originalPrice: 59.95,
    salePrice: 19.95,
    rating: 4.2,
  },
];